name: "{GitHub username}'s Docker container action example"
description: 'Greets someone and always return 42.'
inputs:
  who-to-greet: # id of input
    description: 'Who I should to greet'
    required: true
    default: 'World'
  outputs:
    answer: # id of output
      description: 'The answer to everything (always 42)'
  runs:
    using: 'docker'
    image: 'Dockerfile'
    args:
      - ${{ inputs.who-to-greet }}
